[package]
name = "dors"
version = "0.1.0"
authors = ["Andrew Klitzke <andrew.klitzke@getbraintree.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
cargo_metadata = "0.9.1"
lazy_static = "1.4.0"
rand = "0.7"
clap = "2.33"
