# Such a simple little Dorsfile for this project!
# This project doesn't need a complicated
# one. Dors was built with other types of projects
# in mind.

[task.test-with-output]
command = "cargo test -- --nocapture"

# Easily do ci tests locally
[task.ci]
command = '''
# Test that we can upgrade from the last version
cargo install --path .

# Invoke dors from fresh cargo
cargo dors test-with-output

# Run extra build checks
cargo clippy -- -D warnings
cargo audit
'''
